---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - util.github.com
  resources:
  - ingestors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - util.github.com
  resources:
  - ingestors/finalizers
  verbs:
  - update
- apiGroups:
  - util.github.com
  resources:
  - ingestors/status
  verbs:
  - get
  - patch
  - update
